version: "3.9"
services: 
    postgres:
        image: postgres:15.1-alpine
        restart: always
        hostname: kong-database
        container_name: kong-database
        environment:
            POSTGRES_USER: "kong"
            POSTGRES_DB: "kong"
            POSTGRES_PASSWORD: "kong"
        ports:
          - "5432:5432"
    kong-bootstrap:
        image: kong:3.1.1-alpine
        hostname: kong-bootstrap
        container_name: kong-bootstrap
        depends_on:
          - postgres
        environment:
            KONG_DATABASE: "postgres"
            KONG_PG_HOST: "kong-database"
            KONG_PG_DATABASE: "kong"
            KONG_PG_USER: "kong"
            KONG_PG_PASSWORD: "kong"
        command: "kong migrations bootstrap"
        restart: 'on-failure'
    kong-gateway:
        image: kong:3.1.1-alpine
        restart: always
        hostname: kong-gateway
        container_name: kong-gateway
        depends_on:
          - kong-bootstrap
        environment:
            KONG_DATABASE: "postgres"
            KONG_PG_HOST: "kong-database"
            KONG_PG_DATABASE: "kong"
            KONG_PG_USER: "kong"
            KONG_PG_PASSWORD: "kong"
            KONG_PROXY_ACCESS_LOG: '/dev/stdout'
            KONG_ADMIN_ACCESS_LOG: '/dev/stdout'
            KONG_PROXY_ERROR_LOG: '/dev/stderr'
            KONG_ADMIN_ERROR_LOG: '/dev/stderr'
            KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
        command: "kong start"
        ports:
          - "8000:8000"
          - "8443:8443"
          - "8001:8001"
          - "8444:8444"
networks:
    default:
        name: kong-net