version: "3.9"
services:
    postgres:
        image: postgres:15.1-alpine
        restart: always
        hostname: keycloak-database
        container_name: keycloak-database
        environment:
            POSTGRES_USER: "keycloak"
            POSTGRES_DB: "keycloak"
            POSTGRES_PASSWORD: "keycloak"
        ports:
          - "5433:5432"
    keycloak:
        image: bitnami/keycloak:latest
        restart: always
        hostname: keycloak
        container_name: keycloak
        depends_on:
          - postgres
        environment:
            KEYCLOAK_ADMIN: "admin"
            KEYCLOAK_ADMIN_PASSWORD: "admin"
            KEYCLOAK_DATABASE_HOST: "keycloak-database"
            KEYCLOAK_DATABASE_NAME: "keycloak"
            KEYCLOAK_DATABASE_USER: "keycloak"
            KEYCLOAK_DATABASE_PASSWORD: "keycloak"
            KEYCLOAK_HTTPS_PORT: "8445"
        ports:
          - "8080:8080"
          - "8445:8445"
networks:
    default:
        name: keycloak-net